services:
  nginx:
    networks:
      default: {}
      edge:
        aliases: [gridplusplus]
  app:
    networks:
      default: {}
      edge: {}

networks:
  edge:
    external: true
    name: ${EDGE_NETWORK}
